"""
Django settings for sockportal__backend project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from corsheaders.defaults import default_headers

from common.constants import (
    AllowedOriginsConstants,
    DatabaseConstants,
    DjangoConstants,
    LDAPConstants,
    RabbitmqConstants,
    RedisConstants,
)

# load_dotenv()
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = DjangoConstants.SECRET_KEY

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]  # AllowedHostsConstants.ALLOWED_HOSTS


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "channels",
]

INSTALLED_APPS += [
    "authentication",
    "tenant",
    "tenantadmin",
    "integration",
]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = AllowedOriginsConstants.ALLOWED_ORIGINS
CORS_ALLOW_HEADERS = list(default_headers) + [
    "access-control-allow-origin",
]


ROOT_URLCONF = "sockportal__backend.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]
REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,  # Fixed page size, clients cannot override
}
WSGI_APPLICATION = "sockportal__backend.wsgi.application"

# ASGI_APPLICATION = "sockportal__backend.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": DatabaseConstants.DATABASE_ENGINE,
        "NAME": DatabaseConstants.DATABASE_NAME,
        "USER": DatabaseConstants.DATABASE_USER,
        "PASSWORD": DatabaseConstants.DATABASE_PASSWORD,
        "HOST": DatabaseConstants.DATABASE_HOST,
        "PORT": DatabaseConstants.DATABASE_PORT,
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": False,
    "BLACKLIST_AFTER_ROTATION": False,
    "UPDATE_LAST_LOGIN": False,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "VERIFYING_KEY": None,
    "AUDIENCE": None,
    "ISSUER": None,
    "JWK_URL": None,
    "LEEWAY": 0,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_HEADER_NAME": "HTTP_AUTHORIZATION",
    "USER_ID_FIELD": "id",
    "USER_ID_CLAIM": "user_id",
    # "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
}


AUTH_USER_MODEL = "authentication.User"

CELERY_BROKER_URL = (
    f"amqp://{RabbitmqConstants.RABBITMQ_DEFAULT_USER}:"
    f"{RabbitmqConstants.RABBITMQ_DEFAULT_PASS}@"
    f"{RabbitmqConstants.RABBITMQ_HOST}:"
    f"{RabbitmqConstants.RABBITMQ_AMQP_PORT}//"
)
CELERY_RESULT_BACKEND = f"redis://{RedisConstants.REDIS_HOST}:{RedisConstants.REDIS_PORT}/0"  # Store task results
CELERY_ACCEPT_CONTENT = ["json"]  # Allow JSON serialization
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "UTC"  # Set timezone (match Django's TIME_ZONE if needed)

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [(RedisConstants.REDIS_HOST, RedisConstants.REDIS_PORT)],
        },
    },
}


CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"redis://{RedisConstants.REDIS_HOST}:{RedisConstants.REDIS_PORT}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    }
}

STATIC_ROOT = os.path.join(BASE_DIR, "static")
STATIC_URL = "/static/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media/")
MEDIA_URL = "/media/"


import ldap
from django_auth_ldap.config import LDAPSearch, PosixGroupType

# AUTH_LDAP_SERVER_URI = f'ldap://{LDAPConstants.LDAP_SERVERS[0]}:{LDAPConstants.LDAP_PORT}'
# AUTH_LDAP_BIND_DN = LDAPConstants.BASE_DN
# AUTH_LDAP_BIND_PASSWORD = 'YourLDAPPassword'
# AUTH_LDAP_USER_SEARCH = LDAPSearch('dc=example,dc=com',ldap.SCOPE_SUBTREE, '(uid=%(user)s)')
# AUTH_LDAP_GROUP_SEARCH = LDAPSearch('dc=example,dc=com',ldap.SCOPE_SUBTREE, '(objectClass=top)')


# AUTH_LDAP_GROUP_TYPE = PosixGroupType(name_attr="cn")
# AUTH_LDAP_MIRROR_GROUPS = True

#     # Populate the Django user from the LDAP directory.
# AUTH_LDAP_REQUIRE_GROUP = "cn=enabled,ou=groups,dc=example,dc=com"

# AUTH_LDAP_USER_ATTR_MAP = {
#         "first_name": "givenName",
#         "last_name": "sn",
#         "email": "mail",
#         "username": "uid",
#         "password": "userPassword",
# }
# AUTH_LDAP_PROFILE_ATTR_MAP = {
#         "home_directory": "homeDirectory"
# }
# AUTH_LDAP_USER_FLAGS_BY_GROUP = {
#         "is_active": "cn=active,ou=groups,dc=example,dc=com",
#         "is_staff": "cn=staff,ou=groups,dc=example,dc=com",


#         "is_superuser": "cn=superuser,ou=groups,dc=example,dc=com"
# }

# AUTH_LDAP_ALWAYS_UPDATE_USER = True
# AUTH_LDAP_FIND_GROUP_PERMS = True
# AUTH_LDAP_CACHE_TIMEOUT = 3600

# AUTH_LDAP_FIND_GROUP_PERMS = True

#     # Keep ModelBackend around for per-user permissions and maybe a local
#     # superuser.
# AUTHENTICATION_BACKENDS = (
#         'django_auth_ldap.backend.LDAPBackend',
#         'django.contrib.auth.backends.ModelBackend',
# )

AUTHENTICATION_BACKENDS = [
    "django_auth_ldap.backend.LDAPBackend",
    "django.contrib.auth.backends.ModelBackend",  # Fallback for local users
]

# LDAP Configuration
AUTH_LDAP_SERVER_URI = [
    f"ldap://{server}:{LDAPConstants.LDAP_PORT}"
    for server in LDAPConstants.LDAP_SERVERS
]
AUTH_LDAP_BIND_DN = LDAPConstants.BASE_DN  # Replace with actual bind user DN
# AUTH_LDAP_BIND_PASSWORD = "bind_user_password"  # Replace with actual password

# User search configuration
AUTH_LDAP_USER_SEARCH = LDAPSearch(
    LDAPConstants.BASE_DN, ldap.SCOPE_SUBTREE, "(sAMAccountName=%(user)s)"
)

# Map LDAP attributes to Django user model
AUTH_LDAP_USER_ATTR_MAP = {
    "first_name": "givenName",
    "last_name": "sn",
    "email": "mail",
}

# Optional: Group-based permissions
AUTH_LDAP_GROUP_SEARCH = LDAPSearch(
    LDAPConstants.BASE_DN, ldap.SCOPE_SUBTREE, "(objectClass=group)"
)
AUTH_LDAP_GROUP_TYPE = PosixGroupType()
AUTH_LDAP_USER_FLAGS_BY_GROUP = {
    "is_active": "CN=ActiveUsers,OU=Groups,OU=Wipro_CSOC,OU=ICT Managed Services Platform,DC=mscloudinfra,DC=com",
    "is_staff": "CN=StaffUsers,OU=Groups,OU=Wipro_CSOC,OU=ICT Managed Services Platform,DC=mscloudinfra,DC=com",
    "is_superuser": "CN=Admins,OU=Groups,OU=Wipro_CSOC,OU=ICT Managed Services Platform,DC=mscloudinfra,DC=com",
}

# LDAP connection options
AUTH_LDAP_CONNECTION_OPTIONS = {
    ldap.OPT_REFERRALS: 0,  # Disable referrals for Active Directory
}

# DRF settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.TokenAuthentication",  # Token-based authentication
        "rest_framework.authentication.SessionAuthentication",  # Optional for browsable API
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",  # Require authentication for API access
    ],
}
