# Generated by Django 5.2 on 2025-04-15 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("tenant", "0007_tenant_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Integration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "integration_type",
                    models.IntegerField(
                        choices=[
                            (1, "SIEM Integration"),
                            (2, "SOAR Integration"),
                            (3, "ITSM Integration"),
                        ],
                        default=1,
                    ),
                ),
                ("instance_name", models.CharField(max_length=100)),
                ("instance_type", models.CharField(max_length=100)),
                ("api_key", models.CharField(max_length=100)),
                ("version", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integrations",
                        to="tenant.tenant",
                    ),
                ),
            ],
        ),
    ]
