# Generated by Django 5.2 on 2025-04-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="itsm_subtype",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Jira"), (2, "Zendesk"), (3, "Other")],
                help_text="Required for ITSM Integration type",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="siem_subtype",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "IBM QRadar"), (2, "Splunk"), (3, "Other")],
                help_text="Required for SIEM Integration type",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="soar_subtype",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "ServiceNow"), (2, "IBM Resilient"), (3, "Other")],
                help_text="Required for SOAR Integration type",
                null=True,
            ),
        ),
    ]
