# Generated by Django 5.2 on 2025-05-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "integration",
            "0002_integration_itsm_subtype_integration_siem_subtype_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="DuIbmQradarTenants",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "db_table": "du_ibm_qradar_tenants",
            },
        ),
    ]
