# Generated by Django 5.2 on 2025-05-05 08:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0003_duibmqradartenants"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DuIbmQradarTenants",
        ),
    ]
