# Generated by Django 5.2 on 2025-05-06 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0004_delete_duibmqradartenants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="tenant",
        ),
        migrations.CreateModel(
            name="IntegrationCredentials",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
                ("ip_address", models.CharField(max_length=100, unique=True)),
                ("port", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="integration.integration",
                    ),
                ),
            ],
        ),
    ]
