# Generated by Django 5.2 on 2025-05-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0005_remove_integration_tenant_integrationcredentials"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="api_key",
        ),
        migrations.AddField(
            model_name="integrationcredentials",
            name="api_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="integrationcredentials",
            name="credential_type",
            field=models.IntegerField(
                choices=[(1, "API Key"), (2, "Username and Password")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="integrationcredentials",
            name="password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="integrationcredentials",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
