# Generated by Django 5.2 on 2025-05-06 06:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0006_remove_integration_api_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="version",
        ),
    ]
