# Generated by Django 5.2 on 2025-05-06 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0007_remove_integration_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="instance_type",
        ),
    ]
