# Generated by Django 5.2 on 2025-05-06 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0008_remove_integration_instance_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationcredentials",
            name="port",
            field=models.IntegerField(default=80),
        ),
    ]
