# Generated by Django 5.2 on 2025-05-06 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0010_integration_admin_integration_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationcredentials",
            name="ip_address",
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
