# Generated by Django 5.2 on 2025-05-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0012_alter_integration_admin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="itsm_subtype",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "M.E ServiceDesk Plus MSP"), (2, "Zendesk"), (3, "Other")],
                help_text="Required for ITSM Integration type",
                null=True,
            ),
        ),
    ]
