# Generated by Django 5.2 on 2025-05-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0013_alter_integration_itsm_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="soar_subtype",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Cortex SOAR"), (2, "IBM Resilient"), (3, "Other")],
                help_text="Required for SOAR Integration type",
                null=True,
            ),
        ),
    ]
