# Generated by Django 5.2 on 2025-06-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="integration_type",
            field=models.IntegerField(
                choices=[
                    (1, "SIEM Integration"),
                    (2, "SOAR Integration"),
                    (3, "ITSM Integration"),
                    (4, "Threat Intelligence"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="integrationcredentials",
            name="credential_type",
            field=models.IntegerField(
                choices=[
                    (1, "API Key"),
                    (2, "Username and Password"),
                    (3, "Secret Key and Access Key"),
                ],
                default=1,
            ),
        ),
    ]
