# Generated by Django 5.2 on 2025-06-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0015_alter_integration_integration_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationcredentials",
            name="access_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="integrationcredentials",
            name="secret_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
