# Generated by Django 5.2 on 2025-06-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0016_integrationcredentials_access_key_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="threat_intelligence_subtype",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "CYWARE")],
                help_text="Required for Threat Intelligence Integration type",
                null=True,
            ),
        ),
    ]
