# Generated by Django 5.2 on 2025-06-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0017_integration_threat_intelligence_subtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationcredentials",
            name="base_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
