# Generated by Django 5.2 on 2025-06-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0018_integrationcredentials_base_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationcredentials",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
