# Generated by Django 5.2 on 2025-06-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0019_alter_integrationcredentials_ip_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integrationcredentials",
            name="base_url",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
