# Generated by Django 5.2 on 2025-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0020_alter_integrationcredentials_base_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="integration_type",
            field=models.IntegerField(
                choices=[
                    (1, "SIEM Integration"),
                    (2, "SOAR Integration"),
                    (3, "ITSM Integration"),
                    (4, "Threat Advisory Integration"),
                ],
                default=1,
            ),
        ),
        migrations.AlterField(
            model_name="integration",
            name="threat_intelligence_subtype",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "DU-CYWARE")],
                help_text="Required for Threat Intelligence Integration type",
                null=True,
            ),
        ),
    ]
