# Generated by Django 5.2 on 2025-09-05 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0021_alter_integration_integration_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="integration",
            name="admin",
        ),
    ]
