# Generated by Django 5.2 on 2025-09-05 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0022_remove_integration_admin"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this integration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_integrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="integration",
            name="modified_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who last modified this integration",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="modified_integrations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
