# Generated by Django 5.2 on 2026-01-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0023_integration_created_by_integration_modified_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="integration",
            name="soar_subtype",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "Cortex SOAR"),
                    (2, "Forti SOAR"),
                    (3, "IBM Resilient"),
                    (4, "Other"),
                ],
                help_text="Required for SOAR Integration type",
                null=True,
            ),
        ),
    ]
