# Generated by Django 5.2 on 2025-04-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
