# Generated by Django 5.2 on 2025-04-10 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0002_tenant_contact_email_tenant_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="TenantRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "role_type",
                    models.IntegerField(choices=[(1, "Super Admin")], default=1),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="tenant.tenant",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TenantRolePermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permission",
                    models.IntegerField(
                        choices=[
                            (1, "Dashboard"),
                            (2, "Chatbot"),
                            (3, "Reports"),
                            (4, "Threat Intelligence"),
                            (5, "Assets"),
                        ]
                    ),
                ),
                ("permission_text", models.CharField(editable=False, max_length=100)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.tenantrole",
                    ),
                ),
            ],
        ),
    ]
