# Generated by Django 5.2 on 2025-04-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0003_tenant_password_alter_tenant_name_tenantrole_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="contact_email",
        ),
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="name",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
