# Generated by Django 5.2 on 2025-04-10 09:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0004_remove_tenant_contact_email_tenant_email_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="email",
        ),
    ]
