# Generated by Django 5.2 on 2025-04-10 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0005_remove_tenant_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
