# Generated by Django 5.2 on 2025-04-15 06:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0007_tenant_tenant"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="email",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="password",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenant",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
