# Generated by Django 5.2 on 2025-04-15 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0008_remove_tenant_email_remove_tenant_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="name",
        ),
    ]
