# Generated by Django 5.2 on 2025-04-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0010_alter_tenant_tenant_alter_tenantrolepermissions_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantrole",
            name="role_type",
            field=models.IntegerField(choices=[(1, "Tenant")], default=1),
        ),
    ]
