# Generated by Django 5.2 on 2025-04-29 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0011_alter_tenantrole_role_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="tenantrole",
            index=models.Index(
                fields=["tenant"], name="tenant_tena_tenant__3ff20e_idx"
            ),
        ),
    ]
