# Generated by Django 5.2 on 2025-05-05 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0012_tenantrole_tenant_tena_tenant__3ff20e_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuIbmQradarTenants",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
            ],
            options={
                "db_table": "du_ibm_qradar_tenants",
            },
        ),
        migrations.AddField(
            model_name="tenant",
            name="qradar_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenants",
                to="tenant.duibmqradartenants",
            ),
        ),
    ]
