# Generated by Django 5.2 on 2025-05-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0013_duibmqradartenants_tenant_qradar_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBMQradarEventCollector",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, default="", max_length=255)),
                ("host_id", models.IntegerField()),
                (
                    "component_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
            ],
            options={
                "db_table": "IBMQradarEventCollector",
            },
        ),
    ]
