# Generated by Django 5.2 on 2025-05-08 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0014_ibmqradareventcollector"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ibmqradareventcollector",
            table="du_ibm_qradar_event_collector",
        ),
    ]
