# Generated by Django 5.2 on 2025-05-08 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0015_alter_ibmqradareventcollector_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="event_collector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenants",
                to="tenant.ibmqradareventcollector",
            ),
        ),
    ]
