# Generated by Django 5.2 on 2025-05-08 08:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0012_alter_integration_admin"),
        ("tenant", "0016_tenant_event_collector"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="integration_id",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="integration.integration",
            ),
        ),
    ]
