# Generated by Django 5.2 on 2025-05-08 08:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0017_tenant_integration_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tenant",
            old_name="integration_id",
            new_name="integration",
        ),
    ]
