# Generated by Django 5.2 on 2025-05-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0018_rename_integration_id_tenant_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
