# Generated by Django 5.2 on 2025-05-12 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0012_alter_integration_admin"),
        ("tenant", "0019_tenant_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="event_collector",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="tenant.ibmqradareventcollector",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="integration",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="integration.integration",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="qradar_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="tenant.duibmqradartenants",
            ),
        ),
    ]
