# Generated by Django 5.2 on 2025-05-12 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0012_alter_integration_admin"),
        ("tenant", "0020_alter_tenant_event_collector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="duibmqradartenants",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_ibm_qradar_tenants",
                to="integration.integration",
            ),
        ),
        migrations.AddField(
            model_name="ibmqradareventcollector",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ibm_qradar_event_collectors",
                to="integration.integration",
            ),
        ),
        migrations.AlterField(
            model_name="duibmqradartenants",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="ibmqradareventcollector",
            name="component_name",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name="ibmqradareventcollector",
            name="name",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
