# Generated by Django 5.2 on 2025-05-14 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0012_alter_integration_admin"),
        ("tenant", "0021_duibmqradartenants_integration_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuITSMTenants",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, default=None, max_length=255)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_itsm_tenants",
                        to="integration.integration",
                    ),
                ),
            ],
        ),
    ]
