# Generated by Django 5.2 on 2025-05-14 08:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0022_duitsmtenants"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="duitsmtenants",
            table="du_itsm_tenants",
        ),
    ]
