# Generated by Django 5.2 on 2025-05-14 11:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0013_alter_integration_itsm_subtype"),
        ("tenant", "0023_alter_duitsmtenants_table"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="event_collector",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="integration",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="qradar_tenant",
        ),
        migrations.AddField(
            model_name="tenant",
            name="event_collectors",
            field=models.ManyToManyField(
                blank=True, to="tenant.ibmqradareventcollector"
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="integrations",
            field=models.ManyToManyField(blank=True, to="integration.integration"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="is_itsm_tenant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tenant",
            name="qradar_tenants",
            field=models.ManyToManyField(blank=True, to="tenant.duibmqradartenants"),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="country",
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_tenants",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="TenantQradarMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_collectors",
                    models.ManyToManyField(
                        blank=True, to="tenant.ibmqradareventcollector"
                    ),
                ),
                (
                    "qradar_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.duibmqradartenants",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenant.tenant"
                    ),
                ),
            ],
            options={
                "unique_together": {("tenant", "qradar_tenant")},
            },
        ),
    ]
