# Generated by Django 5.2 on 2025-05-15 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0013_alter_integration_itsm_subtype"),
        ("tenant", "0024_remove_tenant_event_collector_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="itsm_tenants",
            field=models.ManyToManyField(blank=True, to="tenant.duitsmtenants"),
        ),
        migrations.CreateModel(
            name="DuSOARTenants",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, default=None, max_length=255)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_soar_tenants",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "du_soar_tenants",
            },
        ),
    ]
