# Generated by Django 5.2 on 2025-05-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
        ("tenant", "0025_tenant_itsm_tenants_dusoartenants"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuCortexSOARTenants",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, default=None, max_length=255)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_cortex_soar_tenants",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "du_cortex_soar_tenants",
            },
        ),
        migrations.DeleteModel(
            name="DuSOARTenants",
        ),
    ]
