# Generated by Django 5.2 on 2025-05-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0026_ducortexsoartenants_delete_dusoartenants"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="soar_tenants",
            field=models.ManyToManyField(blank=True, to="tenant.ducortexsoartenants"),
        ),
    ]
