# Generated by Django 5.2 on 2025-05-15 10:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0027_tenant_soar_tenants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="is_itsm_tenant",
        ),
    ]
