# Generated by Django 5.2 on 2025-05-19 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
        ("tenant", "0028_remove_tenant_is_itsm_tenant"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBMQradarAssests",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("name", models.CharField(blank=True, default=None, max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("average_eps", models.IntegerField()),
                (
                    "creation_date",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "modified_date",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "last_event_time",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ibm_qradar_assets",
                        to="integration.integration",
                    ),
                ),
            ],
        ),
    ]
