# Generated by Django 5.2 on 2025-05-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0029_ibmqradarassests"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassests",
            name="target_event_collector_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="ibmqradarassests",
            name="average_eps",
            field=models.IntegerField(default=0),
        ),
    ]
