# Generated by Django 5.2 on 2025-05-19 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0030_ibmqradarassests_target_event_collector_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassests",
            name="event_collector_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ibm_qradar_assets",
                to="tenant.ibmqradareventcollector",
            ),
        ),
    ]
