# Generated by Django 5.2 on 2025-05-19 07:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0031_ibmqradarassests_event_collector_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ibmqradarassests",
            table="ibm_qradar_assets",
        ),
    ]
