# Generated by Django 5.2 on 2025-05-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0032_alter_ibmqradarassests_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassests",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ibmqradarassests",
            name="sending_ip",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
