# Generated by Django 5.2 on 2025-05-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0033_ibmqradarassests_enabled_ibmqradarassests_sending_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradarassests",
            name="sending_ip",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
