# Generated by Django 5.2 on 2025-05-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0034_alter_ibmqradarassests_sending_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassests",
            name="status",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
