# Generated by Django 5.2 on 2025-05-19 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0035_ibmqradarassests_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradarassests",
            name="status",
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
