# Generated by Django 5.2 on 2025-05-19 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
        ("tenant", "0036_alter_ibmqradarassests_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradarassests",
            name="event_collector_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_ibm_qradar_assets",
                to="tenant.ibmqradareventcollector",
            ),
        ),
        migrations.AlterField(
            model_name="ibmqradarassests",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_ibm_qradar_assets",
                to="integration.integration",
            ),
        ),
        migrations.AlterModelTable(
            name="ibmqradarassests",
            table="du_ibm_qradar_assets",
        ),
    ]
