# Generated by Django 5.2 on 2025-05-19 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
        ("tenant", "0037_alter_ibmqradarassests_event_collector_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradareventcollector",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_ibm_qradar_event_collectors",
                to="integration.integration",
            ),
        ),
    ]
