# Generated by Django 5.2 on 2025-05-19 10:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0038_alter_ibmqradareventcollector_integration"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ibmqradarassests",
            old_name="event_collector_id",
            new_name="event_collector",
        ),
    ]
