# Generated by Django 5.2 on 2025-05-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0039_rename_event_collector_id_ibmqradarassests_event_collector"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradarassests",
            name="event_collector",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.ibmqradareventcollector",
            ),
        ),
    ]
