# Generated by Django 5.2 on 2025-05-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0040_alter_ibmqradarassests_event_collector"),
    ]

    operations = [
        migrations.CreateModel(
            name="DUCortexSOARIncidentModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                ("account", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("occured", models.DateTimeField(blank=True, null=True)),
                ("closed", models.DateTimeField(blank=True, null=True)),
                ("sla", models.IntegerField(blank=True, null=True)),
                ("severity", models.IntegerField(blank=True, null=True)),
                ("investigated_id", models.IntegerField(blank=True, null=True)),
                (
                    "closing_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("owner", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "playbook_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "incident_phase",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "incidentpriority",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("incidenttta", models.DateTimeField(blank=True, null=True)),
                ("incidentttdn", models.DateTimeField(blank=True, null=True)),
                ("incidentttn", models.DateTimeField(blank=True, null=True)),
                ("initialnotification", models.BooleanField(null=True)),
                ("listofrulesoffense", models.JSONField(blank=True, null=True)),
                ("logsourcetype", models.JSONField(blank=True, null=True)),
                ("lowlevelcategoriesevents", models.JSONField(blank=True, null=True)),
                ("sourceips", models.JSONField(blank=True, null=True)),
                (
                    "qradarcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "qradarsubcategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "ttacalculation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
            ],
            options={
                "db_table": "du_cortex_soar_tickets",
            },
        ),
    ]
