# Generated by Django 5.2 on 2025-05-20 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0041_ducortexsoarincidentmodel"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="ducortexsoarincidentmodel",
            table="du_cortex_soar_incidents",
        ),
    ]
