# Generated by Django 5.2 on 2025-05-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0042_alter_ducortexsoarincidentmodel_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuITSMTickets",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("short_description", models.TextField()),
                ("subject", models.TextField()),
                ("is_overdue", models.BooleanField(default=False)),
                (
                    "creation_date",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "created_by_name",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("account_id", models.IntegerField()),
                ("status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "du_itsm_tickets",
            },
        ),
        migrations.AlterField(
            model_name="ducortexsoarincidentmodel",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
