# Generated by Django 5.2 on 2025-05-20 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
        ("tenant", "0043_duitsmtickets_alter_ducortexsoarincidentmodel_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ducortexsoarincidentmodel",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_cortex_soar_incidents",
                to="integration.integration",
            ),
        ),
    ]
