# Generated by Django 5.2 on 2025-05-20 12:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0044_ducortexsoarincidentmodel_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="ducortexsoarincidentmodel",
            name="account_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
