# Generated by Django 5.2 on 2025-05-22 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0046_ducortexsoarincidentfinalmodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="duitsmtenants",
            name="db_id",
        ),
        migrations.CreateModel(
            name="IBMQradarOffense",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("event_count", models.IntegerField(default=0)),
                ("flow_count", models.IntegerField(default=0)),
                (
                    "assigned_to",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("security_category_count", models.IntegerField(default=0)),
                ("follow_up", models.BooleanField(default=False)),
                ("source_address_ids", models.JSONField(default=list)),
                ("source_count", models.IntegerField(default=0)),
                ("inactive", models.BooleanField(default=False)),
                ("protected", models.BooleanField(default=False)),
                (
                    "closing_user",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("destination_networks", models.JSONField(default=list)),
                (
                    "source_network",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("category_count", models.IntegerField(default=0)),
                ("close_time", models.BigIntegerField(blank=True, null=True)),
                ("remote_destination_count", models.IntegerField(default=0)),
                ("start_time", models.BigIntegerField()),
                ("magnitude", models.IntegerField(default=0)),
                ("last_updated_time", models.BigIntegerField()),
                ("last_persisted_time", models.BigIntegerField()),
                ("first_persisted_time", models.BigIntegerField()),
                ("credibility", models.IntegerField(default=0)),
                ("severity", models.IntegerField(default=0)),
                ("policy_category_count", models.IntegerField(default=0)),
                ("closing_reason_id", models.IntegerField(blank=True, null=True)),
                ("device_count", models.IntegerField(default=0)),
                ("offense_type", models.IntegerField(default=0)),
                ("relevance", models.IntegerField(default=0)),
                (
                    "offense_source",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("local_destination_address_ids", models.JSONField(default=list)),
                ("local_destination_count", models.IntegerField(default=0)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("categories", models.JSONField(default=list)),
                ("rules", models.JSONField(default=list)),
                (
                    "assests",
                    models.ManyToManyField(
                        related_name="offenses", to="tenant.ibmqradarassests"
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offenses",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_offenses",
            },
        ),
    ]
