# Generated by Django 5.2 on 2025-05-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
        ("tenant", "0047_remove_duitsmtenants_db_id_ibmqradaroffense"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradaroffense",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_ibm_qradar_offenses",
                to="integration.integration",
            ),
        ),
        migrations.AlterField(
            model_name="ibmqradaroffense",
            name="assests",
            field=models.ManyToManyField(
                related_name="du_ibm_qradar_offenses", to="tenant.ibmqradarassests"
            ),
        ),
        migrations.AlterField(
            model_name="ibmqradaroffense",
            name="tenant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_ibm_qradar_offenses",
                to="tenant.duibmqradartenants",
            ),
        ),
    ]
