# Generated by Django 5.2 on 2025-05-22 07:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0048_ibmqradaroffense_integration_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ibmqradaroffense",
            old_name="tenant",
            new_name="qradar_tenant_domain",
        ),
    ]
