# Generated by Django 5.2 on 2025-05-22 09:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0049_rename_tenant_ibmqradaroffense_qradar_tenant_domain"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DUCortexSOARIncidentModel",
        ),
    ]
