# Generated by Django 5.2 on 2025-05-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0050_delete_ducortexsoarincidentmodel"),
    ]

    operations = [
        migrations.AddField(
            model_name="duitsmtenants",
            name="db_id",
            field=models.IntegerField(default=None, unique=True),
        ),
    ]
