# Generated by Django 5.2 on 2025-05-22 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0051_duitsmtenants_db_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="DuITSMFinalTickets",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("short_description", models.TextField()),
                ("subject", models.TextField()),
                ("is_overdue", models.BooleanField(default=False)),
                (
                    "creation_date",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "created_by_name",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "account_name",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("status", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "itsm_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.duitsmtenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_itsm_final_tickets",
            },
        ),
    ]
