# Generated by Django 5.2 on 2025-05-22 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
        ("tenant", "0052_duitsmfinaltickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="duitsmfinaltickets",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_itsm_final_tickets",
                to="integration.integration",
            ),
        ),
        migrations.AlterField(
            model_name="duitsmfinaltickets",
            name="itsm_tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_itsm_final_tickets",
                to="tenant.duitsmtenants",
            ),
        ),
    ]
