# Generated by Django 5.2 on 2025-05-23 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0053_duitsmfinaltickets_integration_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DuITSMTickets",
        ),
    ]
