# Generated by Django 5.2 on 2025-05-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0054_delete_duitsmtickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassests",
            name="type_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
