# Generated by Django 5.2 on 2025-05-26 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
        ("tenant", "0055_ibmqradarassests_type_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBMQradarLogSourceTypes",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_log_source_types",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "ibm_qradar_log_source_types",
                "ordering": ["-created_at"],
            },
        ),
    ]
