# Generated by Django 5.2 on 2025-05-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0056_ibmqradarlogsourcetypes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradarlogsourcetypes",
            name="version",
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
