# Generated by Django 5.2 on 2025-05-26 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0057_alter_ibmqradarlogsourcetypes_version"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ibmqradarassests",
            name="type_id",
        ),
    ]
