# Generated by Django 5.2 on 2025-05-26 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0058_remove_ibmqradarassests_type_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassests",
            name="log_source_type",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tenant.ibmqradarlogsourcetypes",
            ),
        ),
    ]
