# Generated by Django 5.2 on 2025-05-30 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0059_ibmqradarassests_log_source_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBMQradarEPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("eps", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_eps",
                        to="tenant.duibmqradartenants",
                    ),
                ),
                (
                    "log_source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_eps",
                        to="tenant.ibmqradarassests",
                    ),
                ),
            ],
        ),
    ]
