# Generated by Django 5.2 on 2025-05-30 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0014_alter_integration_soar_subtype"),
        ("tenant", "0060_ibmqradareps"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradareps",
            name="Integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_ibm_qradar_eps",
                to="integration.integration",
            ),
        ),
        migrations.AlterModelTable(
            name="ibmqradareps",
            table="du_ibm_qradar_eps",
        ),
    ]
