# Generated by Django 5.2 on 2025-05-30 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0061_ibmqradareps_integration_alter_ibmqradareps_table"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ibmqradareps",
            old_name="Integration",
            new_name="integration",
        ),
    ]
