# Generated by Django 5.2 on 2025-06-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0062_rename_integration_ibmqradareps_integration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
