# Generated by Django 5.2 on 2025-06-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0063_alter_tenant_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
