# Generated by Django 5.2 on 2025-06-02 08:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0017_integration_threat_intelligence_subtype"),
        ("tenant", "0064_alter_tenant_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.CharField(max_length=64, unique=True)),
                ("title", models.TextField()),
                ("status", models.TextField()),
                ("published_time", models.DateTimeField()),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "threat_intelligence_alerts",
                "indexes": [
                    models.Index(fields=["db_id"], name="threat_inte_db_id_7854c0_idx")
                ],
            },
        ),
    ]
