# Generated by Django 5.2 on 2025-06-02 10:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0065_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="alert",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="alert",
            name="published_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
