# Generated by Django 5.2 on 2025-06-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0066_alert_created_at_alert_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantrole",
            name="role_type",
            field=models.IntegerField(
                choices=[(1, "Tenant_ADMIN"), (2, "Tenant_USER")], default=1
            ),
        ),
    ]
