# Generated by Django 5.2 on 2025-06-03 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0067_alter_tenantrole_role_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_defualt_threat_intel",
            field=models.BooleanField(default=True),
        ),
    ]
