# Generated by Django 5.2 on 2025-06-03 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0068_tenant_is_defualt_threat_intel"),
    ]

    operations = [
        migrations.CreateModel(
            name="ThreatIntelligenceTenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "threat_intelligence",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "CYWARE")],
                        help_text="Required for Threat Intelligence Integration type",
                        null=True,
                    ),
                ),
                ("access_key", models.CharField(blank=True, max_length=100, null=True)),
                ("secret_key", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "base_url",
                    models.CharField(
                        blank=True, max_length=100, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenants",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "threat_intelligence_tenants",
            },
        ),
    ]
