# Generated by Django 5.2 on 2025-06-03 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0070_alter_threatintelligencetenant_threat_intelligence"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threatintelligencetenant",
            name="access_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="threatintelligencetenant",
            name="secret_key",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.CreateModel(
            name="ThreatIntelligenceTenantAlerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.CharField(max_length=64, unique=True)),
                ("title", models.TextField()),
                ("status", models.TextField()),
                ("published_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "threat_intelligence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.threatintelligencetenant",
                    ),
                ),
            ],
            options={
                "db_table": "threat_intelligence_tenant_alerts",
            },
        ),
    ]
