# Generated by Django 5.2 on 2025-06-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0071_alter_threatintelligencetenant_access_key_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="threatintelligencetenant",
            name="tenant",
        ),
        migrations.AddField(
            model_name="threatintelligencetenant",
            name="tenants",
            field=models.ManyToManyField(
                related_name="custom_threat_intels", to="tenant.tenant"
            ),
        ),
    ]
