# Generated by Django 5.2 on 2025-06-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0072_remove_threatintelligencetenant_tenant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threatintelligencetenant",
            name="access_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="threatintelligencetenant",
            name="base_url",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="threatintelligencetenant",
            name="secret_key",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="threatintelligencetenant",
            unique_together={("access_key", "secret_key", "base_url")},
        ),
    ]
