# Generated by Django 5.2 on 2025-06-10 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0020_alter_integrationcredentials_base_url"),
        ("tenant", "0074_cywaretag"),
    ]

    operations = [
        migrations.CreateModel(
            name="CywareGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.CharField(max_length=64, unique=True)),
                ("group_name", models.CharField(max_length=255)),
                ("group_tlp", models.CharField(max_length=20)),
                ("group_type", models.CharField(max_length=50)),
                ("allowed_for_intel_submission", models.BooleanField(default=False)),
                ("allowed_for_rfi_submission", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "cyware_groups",
            },
        ),
    ]
