# Generated by Django 5.2 on 2025-06-10 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0020_alter_integrationcredentials_base_url"),
        ("tenant", "0076_customfield"),
    ]

    operations = [
        migrations.CreateModel(
            name="CywareCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.CharField(unique=True)),
                ("field_name", models.CharField(max_length=255)),
                ("field_label", models.CharField(max_length=255)),
                ("field_type", models.CharField(max_length=50)),
                ("field_description", models.TextField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "cyware_custom_fields",
            },
        ),
        migrations.DeleteModel(
            name="CustomField",
        ),
    ]
