# Generated by Django 5.2 on 2025-06-10 09:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0077_cywarecustomfield_delete_customfield"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cywarecustomfield",
            name="db_id",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
