# Generated by Django 5.2 on 2025-06-10 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0079_cywarecategories"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CywareCategories",
        ),
    ]
