# Generated by Django 5.2 on 2025-06-10 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0020_alter_integrationcredentials_base_url"),
        ("tenant", "0080_delete_cywarecategories"),
    ]

    operations = [
        migrations.CreateModel(
            name="CywareCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.CharField(max_length=64, unique=True)),
                ("category_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_categories",
                        to="tenant.cywarecustomfield",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integration.integration",
                    ),
                ),
                (
                    "required_fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_categories",
                        to="tenant.cywarecustomfield",
                    ),
                ),
                (
                    "threat_indicator_fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="threat_categories",
                        to="tenant.cywarecustomfield",
                    ),
                ),
            ],
            options={
                "db_table": "cyware_categories",
            },
        ),
    ]
