# Generated by Django 5.2 on 2025-06-10 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0020_alter_integrationcredentials_base_url"),
        ("tenant", "0081_cywarecategories"),
    ]

    operations = [
        migrations.CreateModel(
            name="CywareAlertDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("short_id", models.CharField(max_length=64, unique=True)),
                ("title", models.CharField(max_length=512)),
                ("content", models.TextField()),
                ("status", models.CharField(max_length=32)),
                ("tlp", models.CharField(max_length=32)),
                ("published_time", models.DateTimeField(blank=True, null=True)),
                ("push_required", models.BooleanField(default=False)),
                ("push_email_notification", models.BooleanField(default=False)),
                (
                    "tracking_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("card_image", models.URLField(blank=True, null=True)),
                ("card_info", models.TextField(blank=True, null=True)),
                ("event", models.JSONField(blank=True, null=True)),
                ("intel_id", models.CharField(blank=True, max_length=255, null=True)),
                ("rfi_id", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "alert",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tenant.alert"
                    ),
                ),
                (
                    "card_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.cywarecategories",
                    ),
                ),
                (
                    "card_groups",
                    models.ManyToManyField(
                        blank=True, related_name="card_alerts", to="tenant.cywaregroup"
                    ),
                ),
                (
                    "card_tag",
                    models.ManyToManyField(
                        blank=True, related_name="tagged_alerts", to="tenant.cywaretag"
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integration.integration",
                    ),
                ),
                (
                    "recipient_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="recipient_alerts",
                        to="tenant.cywaregroup",
                    ),
                ),
            ],
            options={
                "db_table": "cyware_alert_details",
            },
        ),
    ]
