# Generated by Django 5.2 on 2025-06-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0082_cywarealertdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradaroffense",
            name="first_persisted_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ibmqradaroffense",
            name="last_persisted_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ibmqradaroffense",
            name="last_updated_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ibmqradaroffense",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
