# Generated by Django 5.2 on 2025-06-12 13:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0083_ibmqradaroffense_first_persisted_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassests",
            name="creation_date_converted",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ibmqradarassests",
            name="last_event_date_converted",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ibmqradarassests",
            name="modified_date_converted",
            field=models.DateField(blank=True, null=True),
        ),
    ]
