# Generated by Django 5.2 on 2025-06-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0084_ibmqradarassests_creation_date_converted_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="ldap_group",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
