# Generated by Django 5.2 on 2025-06-16 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0085_tenant_ldap_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="industry",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
