# Generated by Django 5.2 on 2025-06-16 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0086_tenant_industry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threatintelligencetenant",
            name="threat_intelligence",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "DU-CYWARE")],
                default=1,
                help_text="Required for Threat Intelligence Integration type",
                null=True,
            ),
        ),
    ]
