# Generated by Django 5.2 on 2025-06-17 06:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0087_alter_threatintelligencetenant_threat_intelligence"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="threatintelligencetenant",
            table="cyware_tenants_tool_integration",
        ),
    ]
