# Generated by Django 5.2 on 2025-06-17 06:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0088_alter_threatintelligencetenant_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="threatintelligencetenantalerts",
            table="cyware_custom_tenant_alerts",
        ),
    ]
