# Generated by Django 5.2 on 2025-06-17 06:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0089_alter_threatintelligencetenantalerts_table"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="alert",
            new_name="cyware_aler_db_id_0c46d3_idx",
            old_name="threat_inte_db_id_7854c0_idx",
        ),
        migrations.AlterModelTable(
            name="alert",
            table="cyware_alerts",
        ),
    ]
