# Generated by Django 5.2 on 2025-06-17 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tenant",
            "0090_rename_threat_inte_db_id_7854c0_idx_cyware_aler_db_id_0c46d3_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CywareTenantTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.UUIDField(unique=True)),
                ("tag_name", models.CharField(max_length=255)),
                ("tag_slug", models.SlugField(max_length=255, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "threat_intelligence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.threatintelligencetenant",
                    ),
                ),
            ],
            options={
                "db_table": "cyware_tenant_tags",
            },
        ),
    ]
