# Generated by Django 5.2 on 2025-06-17 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0091_cywaretenanttag"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="cywaretenanttag",
            table="cyware_tags_tenant",
        ),
        migrations.CreateModel(
            name="CywareTenantGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.CharField(max_length=64, unique=True)),
                ("group_name", models.CharField(max_length=255)),
                ("group_tlp", models.CharField(max_length=20)),
                ("group_type", models.CharField(max_length=50)),
                ("allowed_for_intel_submission", models.BooleanField(default=False)),
                ("allowed_for_rfi_submission", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "threat_intelligence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.threatintelligencetenant",
                    ),
                ),
            ],
            options={
                "db_table": "cyware_groups_tenant",
            },
        ),
    ]
