# Generated by Django 5.2 on 2025-06-17 07:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0092_alter_cywaretenanttag_table_cywaretenantgroup"),
    ]

    operations = [
        migrations.AddField(
            model_name="ducortexsoarincidentfinalmodel",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ducortexsoarincidentfinalmodel",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="CywareTenantCustomField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.CharField(max_length=64, unique=True)),
                ("field_name", models.CharField(max_length=255)),
                ("field_label", models.CharField(max_length=255)),
                ("field_type", models.CharField(max_length=50)),
                ("field_description", models.TextField(blank=True, null=True)),
                ("is_system", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "threat_intelligence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.threatintelligencetenant",
                    ),
                ),
            ],
            options={
                "db_table": "cyware_custom_fields_tenant",
            },
        ),
    ]
