# Generated by Django 5.2 on 2025-06-17 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0093_ducortexsoarincidentfinalmodel_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CywareTenantCategories",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.CharField(max_length=64, unique=True)),
                ("category_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "additional_fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="additional_categories_tenant",
                        to="tenant.cywaretenantcustomfield",
                    ),
                ),
                (
                    "required_fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="required_categories_tenant",
                        to="tenant.cywaretenantcustomfield",
                    ),
                ),
                (
                    "threat_indicator_fields",
                    models.ManyToManyField(
                        blank=True,
                        related_name="threat_categories_tenant",
                        to="tenant.cywaretenantcustomfield",
                    ),
                ),
                (
                    "threat_intelligence",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.threatintelligencetenant",
                    ),
                ),
            ],
            options={
                "db_table": "cyware_categories_tenant",
            },
        ),
    ]
