# Generated by Django 5.2 on 2025-06-17 08:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0094_cywaretenantcategories"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="threatintelligencetenantalerts",
            table="cyware_alerts_tenant",
        ),
    ]
