# Generated by Django 5.2 on 2025-06-17 08:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0096_cywaretenantalertdetails"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CywareTenantAlertDetails",
        ),
    ]
