# Generated by Django 5.2 on 2025-06-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0098_cywaretenantalertdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantqradarmapping",
            name="contracted_volume",
            field=models.FloatField(
                blank=True,
                help_text="Value of contracted volume based on the selected type",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenantqradarmapping",
            name="contracted_volume_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "EPS"), (2, "GB/D")],
                help_text="Type of contracted volume: EPS or GB/day",
                null=True,
            ),
        ),
    ]
