# Generated by Django 5.2 on 2025-06-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0099_tenantqradarmapping_contracted_volume_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DefaultSoarSlaMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sla_level",
                    models.IntegerField(
                        choices=[
                            (4, "P1 - Critical"),
                            (3, "P2 - High"),
                            (2, "P3 - Medium"),
                            (1, "P4 - Low"),
                        ],
                        unique=True,
                    ),
                ),
                ("tta_minutes", models.IntegerField(help_text="Time to Acknowledge")),
                ("ttn_minutes", models.IntegerField(help_text="Time to Notify")),
                (
                    "ttdn_minutes",
                    models.IntegerField(help_text="Time to Detection/Neutralization"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "default_soar_sla_metrics",
            },
        ),
    ]
