# Generated by Django 5.2 on 2025-06-18 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0100_defaultsoarslametric"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="is_default_sla",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="SoarTenantSlaMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sla_level",
                    models.IntegerField(
                        choices=[
                            (4, "P1 - Critical"),
                            (3, "P2 - High"),
                            (2, "P3 - Medium"),
                            (1, "P4 - Low"),
                        ]
                    ),
                ),
                (
                    "tta_minutes",
                    models.PositiveIntegerField(help_text="Time to Acknowledge"),
                ),
                (
                    "ttn_minutes",
                    models.PositiveIntegerField(help_text="Time to Notify"),
                ),
                (
                    "ttdn_minutes",
                    models.PositiveIntegerField(help_text="Time to Detect/Neutralize"),
                ),
                (
                    "soar_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sla_metrics",
                        to="tenant.ducortexsoartenants",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="soar_sla_metrics",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "db_table": "soar_tenant_sla_metrics",
                "unique_together": {("tenant", "soar_tenant", "sla_level")},
            },
        ),
    ]
