# Generated by Django 5.2 on 2025-06-18 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0101_tenant_is_default_sla_soartenantslametric"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="is_default_sla",
            field=models.BooleanField(default=True),
        ),
    ]
