# Generated by Django 5.2 on 2025-06-23 12:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0021_alter_integration_integration_type_and_more"),
        ("tenant", "0102_alter_tenant_is_default_sla"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ducortexsoarincidentfinalmodel",
            name="db_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="ducortexsoarincidentfinalmodel",
            constraint=models.UniqueConstraint(
                fields=("account", "db_id"), name="unique_account_db_id"
            ),
        ),
    ]
