# Generated by Django 5.2 on 2025-06-30 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0021_alter_integration_integration_type_and_more"),
        ("tenant", "0106_alter_defaultsoarslametric_sla_level_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="event_collectors",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="industry",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="integrations",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="is_default_sla",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="is_defualt_threat_intel",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="itsm_tenants",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="qradar_tenants",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="soar_tenants",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tenants_created_by",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100, unique=True)),
                ("is_defualt_threat_intel", models.BooleanField(default=True)),
                ("phone_number", models.CharField(blank=True, max_length=20)),
                ("industry", models.CharField(blank=True, max_length=100)),
                ("is_default_sla", models.BooleanField(default=True)),
                ("country", models.CharField(blank=True, max_length=2)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companies_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event_collectors",
                    models.ManyToManyField(
                        blank=True, to="tenant.ibmqradareventcollector"
                    ),
                ),
                (
                    "integrations",
                    models.ManyToManyField(blank=True, to="integration.integration"),
                ),
                (
                    "itsm_tenants",
                    models.ManyToManyField(blank=True, to="tenant.duitsmtenants"),
                ),
                (
                    "qradar_tenant",
                    models.ManyToManyField(blank=True, to="tenant.duibmqradartenants"),
                ),
                (
                    "soar_tenants",
                    models.ManyToManyField(blank=True, to="tenant.ducortexsoartenants"),
                ),
            ],
            options={
                "db_table": "companies",
            },
        ),
        migrations.AlterUniqueTogether(
            name="tenantqradarmapping",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tenant",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tenants",
                to="tenant.company",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tenantqradarmapping",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="qradar_mappings",
                to="tenant.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tenantqradarmapping",
            unique_together={("company", "qradar_tenant")},
        ),
        migrations.RemoveField(
            model_name="tenantqradarmapping",
            name="tenant",
        ),
    ]
