# Generated by Django 5.2 on 2025-06-30 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0107_remove_tenant_event_collectors_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="threatintelligencetenant",
            name="tenants",
        ),
        migrations.AddField(
            model_name="threatintelligencetenant",
            name="company",
            field=models.OneToOneField(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_intelligence_tenants",
                to="tenant.company",
            ),
            preserve_default=False,
        ),
    ]
