# Generated by Django 5.2 on 2025-06-30 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0108_remove_threatintelligencetenant_tenants_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="soartenantslametric",
            unique_together={("soar_tenant", "sla_level")},
        ),
        migrations.RemoveField(
            model_name="soartenantslametric",
            name="tenant",
        ),
    ]
