# Generated by Django 5.2 on 2025-06-30 07:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0109_alter_soartenantslametric_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="soartenantslametric",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="soartenantslametric",
            name="company",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="soar_sla_metrics",
                to="tenant.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="soartenantslametric",
            unique_together={("company", "soar_tenant", "sla_level")},
        ),
    ]
