# Generated by Django 4.2.16 on 2025-07-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0021_alter_integration_integration_type_and_more"),
        ("tenant", "0113_correlatedeventlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyCorrelatedEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week", models.CharField(max_length=10)),
                ("weekly_count", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "integration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integration.integration",
                    ),
                ),
                (
                    "qradar_tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "weekly_correlated_event_log",
            },
        ),
    ]
