# Generated by Django 4.2.16 on 2025-07-02 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0021_alter_integration_integration_type_and_more'),
        ('tenant', '0114_weeklycorrelatedeventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_suspicious_events', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'suspicious_event_log',
            },
        ),
    ]
