# Generated by Django 4.2.16 on 2025-07-02 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0021_alter_integration_integration_type_and_more'),
        ('tenant', '0116_doseventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopDosEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('event_count', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'top_dos_event_log',
            },
        ),
        migrations.CreateModel(
            name='DailyEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_count', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'daily_event_log',
            },
        ),
    ]
