# Generated by Django 4.2.16 on 2025-07-02 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0021_alter_integration_integration_type_and_more'),
        ('tenant', '0119_dailyclosurereasonlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyAvgEpsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(max_length=7)),
                ('week_start', models.CharField(max_length=6)),
                ('weekly_avg_eps', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'weekly_avg_eps_log',
            },
        ),
        migrations.CreateModel(
            name='MonthlyAvgEpsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_avg_eps', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'monthly_avg_eps_log',
            },
        ),
        migrations.CreateModel(
            name='LastMonthAvgEpsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_month_avg_eps', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'last_month_avg_eps_log',
            },
        ),
    ]
