# Generated by Django 4.2.16 on 2025-07-02 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0021_alter_integration_integration_type_and_more'),
        ('tenant', '0120_weeklyavgepslog_monthlyavgepslog_lastmonthavgepslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalTrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_traffic', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'total_traffic_log',
            },
        ),
        migrations.CreateModel(
            name='TopDestinationConnectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(max_length=45)),
                ('connection_count', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'top_destination_connection_log',
            },
        ),
        migrations.CreateModel(
            name='DestinationAddressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(max_length=45)),
                ('address_count', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'destination_address_log',
            },
        ),
        migrations.CreateModel(
            name='DailyEventCountLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_date', models.DateField()),
                ('daily_count', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'daily_event_count_log',
            },
        ),
    ]
