# Generated by Django 5.2 on 2025-07-08 08:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0122_chatmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="duitsmfinaltickets",
            name="soar_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
