# Generated by Django 5.2 on 2025-07-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0123_duitsmfinaltickets_soar_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customereps",
            name="customer",
            field=models.CharField(max_length=255),
        ),
    ]
