# Generated by Django 5.2 on 2025-07-09 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0124_alter_customereps_customer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customereps",
            name="customer",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
