# Generated by Django 4.2.16 on 2025-07-10 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0021_alter_integration_integration_type_and_more'),
        ('tenant', '0125_alter_customereps_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuccessfulLogonEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('logon_type', models.TextField()),
                ('source_ip', models.CharField(max_length=45)),
                ('log_source', models.CharField(max_length=255)),
                ('event_count', models.FloatField()),
                ('full_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'db_table': 'successful_logon_events',
                'indexes': [models.Index(fields=['username'], name='successful__usernam_6b9f3d_idx'), models.Index(fields=['source_ip'], name='successful__source__84252b_idx'), models.Index(fields=['full_date'], name='successful__full_da_e286ba_idx')],
            },
        ),
    ]
