# Generated by Django 4.2.16 on 2025-07-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0021_alter_integration_integration_type_and_more'),
        ('tenant', '0126_successfullogonevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteUsersCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_remote_users', models.FloatField()),
                ('full_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('integration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.integration')),
                ('qradar_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenant.duibmqradartenants')),
            ],
            options={
                'verbose_name_plural': 'Remote Users Counts',
                'db_table': 'remote_users_count',
            },
        ),
    ]
