# Generated by Django 5.2 on 2025-07-10 12:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0127_remoteuserscount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doseventlog",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
