# Generated by Django 4.2.9 on 2025-07-10 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0130_alter_suspiciouseventlog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topdoseventlog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
