# Generated by Django 4.2.9 on 2025-07-11 02:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0137_alter_weeklyavgepslog_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totaltrafficlog',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
