# Generated by Django 5.2 on 2025-07-17 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0021_alter_integration_integration_type_and_more"),
        ("tenant", "0144_sourceipgeolocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="DUSoarNotes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.IntegerField(unique=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(blank=True, null=True)),
                ("user", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "incident_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tenant.ducortexsoarincidentfinalmodel",
                    ),
                ),
                (
                    "integration_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "notes",
            },
        ),
    ]
