# Generated by Django 5.2 on 2025-07-17 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0145_dusoarnotes"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dusoarnotes",
            old_name="incident_id",
            new_name="incident",
        ),
        migrations.RenameField(
            model_name="dusoarnotes",
            old_name="integration_id",
            new_name="integration",
        ),
    ]
