# Generated by Django 4.2.9 on 2025-07-17 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0146_rename_incident_id_dusoarnotes_incident_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ducortexsoarincidentfinalmodel',
            name='itsmsyncstatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
