# Generated by Django 4.2.9 on 2025-07-17 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0147_ducortexsoarincidentfinalmodel_itsmsyncstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ducortexsoarincidentfinalmodel',
            old_name='itsmsyncstatus',
            new_name='itsm_sync_status',
        ),
    ]
