# Generated by Django 5.2 on 2025-07-17 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tenant",
            "0148_rename_itsmsyncstatus_ducortexsoarincidentfinalmodel_itsm_sync_status",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="dusoarnotes",
            name="incident",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="tenant.ducortexsoarincidentfinalmodel",
            ),
        ),
    ]
