# Generated by Django 5.2 on 2025-07-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0149_alter_dusoarnotes_incident"),
    ]

    operations = [
        migrations.AddField(
            model_name="dusoarnotes",
            name="account",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="dusoarnotes",
            unique_together={("db_id", "account", "user")},
        ),
    ]
