# Generated by Django 5.2 on 2025-07-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0150_dusoarnotes_account_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ibmqradareps",
            old_name="eps",
            new_name="average_eps",
        ),
        migrations.RemoveField(
            model_name="ibmqradareps",
            name="log_source",
        ),
        migrations.AddField(
            model_name="ibmqradareps",
            name="peak_eps",
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name="ibmqradareps",
            name="qradar_start_time",
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
