# Generated by Django 5.2 on 2025-07-21 05:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0151_rename_eps_ibmqradareps_average_eps_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="dusoarnotes",
            unique_together={("db_id", "account", "user", "incident")},
        ),
    ]
