# Generated by Django 5.2 on 2025-07-21 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0152_alter_dusoarnotes_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="ducortexsoarincidentfinalmodel",
            name="mitre_tactic",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="ducortexsoarincidentfinalmodel",
            name="mitre_technique",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
