# Generated by Django 5.2 on 2025-07-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0153_ducortexsoarincidentfinalmodel_mitre_tactic_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ducortexsoarincidentfinalmodel",
            name="configuration_item",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
