# Generated by Django 5.2 on 2025-07-21 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0154_ducortexsoarincidentfinalmodel_configuration_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dusoarnotes",
            name="db_id",
            field=models.CharField(unique=True),
        ),
    ]
