# Generated by Django 5.2 on 2025-07-22 08:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0155_alter_dusoarnotes_db_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ibmqradareps",
            old_name="qradar_start_time",
            new_name="qradar_end_time",
        ),
    ]
