# Generated by Django 4.2.9 on 2025-07-24 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0156_rename_qradar_start_time_ibmqradareps_qradar_end_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBMQraderDomainHighLevelCategoryCount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("event_id", models.IntegerField(unique=True)),
                ("start_time", models.DateTimeField()),
                (
                    "high_level_category",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "event_name",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_domains",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_domain_high_level_category_count",
            },
        ),
    ]
