# Generated by Django 5.2 on 2025-07-27 05:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0156_rename_qradar_start_time_ibmqradareps_qradar_end_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradareps",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.CreateModel(
            name="IBMQraderAEPEntraAuthentication",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                (
                    "event_name",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("user", models.CharField(blank=True, default=None, max_length=20)),
                (
                    "low_level_category",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "total_event_count",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_aep_authentication",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_aep_authentication_data",
            },
        ),
        migrations.CreateModel(
            name="IBMQraderAllowedInbounds",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                (
                    "source_ip",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "destination_ip",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "destination_port",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                (
                    "destination_country_and_region_count",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=20)),
                (
                    "total_event_count",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_allowed_inbounds",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_allowed_inbounds_data",
            },
        ),
        migrations.CreateModel(
            name="IBMQraderAllowedOutbounds",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                (
                    "source_ip",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "destination_ip",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "destination_port",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                (
                    "destination_country_and_region",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=20)),
                (
                    "total_event_count",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_allowed_outbounds",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_allowed_outbounds_data",
            },
        ),
        migrations.CreateModel(
            name="IBMQraderCategoryWiseData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                (
                    "log_source",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_domains_for_category_wise_data",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_category_wise_data",
            },
        ),
        migrations.CreateModel(
            name="IBMQraderCorelatedEvents",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                (
                    "event_name",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "magnitude_maximum",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                (
                    "total_event_count",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_corelated_events",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_corelated_events_data",
            },
        ),
        migrations.CreateModel(
            name="IBMQraderDomainHighLevelCategoryCount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                (
                    "high_level_category",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "event_name",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_domains",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_domain_high_level_category_count",
            },
        ),
        migrations.CreateModel(
            name="IBMQraderSensitiveData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                (
                    "source_ip",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "destination_ip",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "destination_port",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                (
                    "destination_country_and_region",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=20)),
                (
                    "total_event_count",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_sensitive_data",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_sensitive_count_wise_data",
            },
        ),
    ]
