# Generated by Django 4.2.9 on 2025-07-24 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0157_ibmqraderdomainhighlevelcategorycount"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ibmqraderdomainhighlevelcategorycount",
            name="event_id",
        ),
    ]
