# Generated by Django 4.2.9 on 2025-07-24 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0158_remove_ibmqraderdomainhighlevelcategorycount_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBMQraderCategoryWiseData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                (
                    "log_source",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_domains_for_category_wise_data",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_category_wise_data",
            },
        ),
    ]
