# Generated by Django 4.2.9 on 2025-07-24 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0159_ibmqradercategorywisedata"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBMQraderSensitiveData",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("start_time", models.DateTimeField()),
                (
                    "source_ip",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "destination_ip",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                (
                    "destination_port",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                (
                    "destination_country_and_region",
                    models.CharField(blank=True, default=None, max_length=255),
                ),
                ("count", models.CharField(blank=True, default=None, max_length=20)),
                (
                    "total_event_count",
                    models.CharField(blank=True, default=None, max_length=20),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_sensitive_data",
                        to="tenant.duibmqradartenants",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_sensitive_count_wise_data",
            },
        ),
    ]
