# Generated by Django 4.2.9 on 2025-07-25 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0162_ibmqraderallowedinbounds"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ibmqraderallowedinbounds",
            old_name="destination_country_and_region",
            new_name="destination_country_and_region_count",
        ),
    ]
