# Generated by Django 5.2 on 2025-07-27 06:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tenant",
            "0163_rename_destination_country_and_region_ibmqraderallowedinbounds_destination_country_and_region_count",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradareps",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
