# Generated by Django 4.2.9 on 2025-07-30 10:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0165_alter_ibmqraderdomainhighlevelcategorycount_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradercategorywisedata",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
