# Generated by Django 4.2.9 on 2025-07-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0169_alter_ibmqraderaepentraauthentication_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqraderaepentraauthentication",
            name="user",
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
