# Generated by Django 4.2.9 on 2025-07-30 11:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0170_alter_ibmqraderaepentraauthentication_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqraderallowedoutbounds",
            name="created_at",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
    ]
