# Generated by Django 4.2.9 on 2025-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0172_alter_ibmqraderallowedinbounds_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatmessage",
            name="is_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
