# Generated by Django 4.2.9 on 2025-08-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0173_chatmessage_is_seen_chatmessage_is_seen_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="chatmessage",
            old_name="is_seen",
            new_name="is_admin_seen",
        ),
        migrations.RenameField(
            model_name="chatmessage",
            old_name="is_seen_at",
            new_name="is_admin_seen_at",
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_tenant_seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatmessage",
            name="is_tenant_seen_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
