# Generated by Django 5.2 on 2025-08-04 06:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0174_rename_is_seen_chatmessage_is_admin_seen_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetsGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("db_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("owner", models.CharField(max_length=100)),
                ("modification_date", models.DateTimeField()),
                ("parent_id", models.BigIntegerField()),
                ("assignable", models.BooleanField(default=False)),
                (
                    "child_group_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BigIntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
        ),
    ]
