# Generated by Django 5.2 on 2025-08-04 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0175_assetsgroup"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AssetsGroup",
            new_name="IBMQradarAssetsGroup",
        ),
        migrations.AlterModelTable(
            name="ibmqradarassetsgroup",
            table="ibm_qradar_assets_group",
        ),
    ]
