# Generated by Django 5.2 on 2025-08-04 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0021_alter_integration_integration_type_and_more"),
        ("tenant", "0176_rename_assetsgroup_ibmqradarassetsgroup_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassetsgroup",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="du_ibm_qradar_assets_groups",
                to="integration.integration",
            ),
        ),
    ]
