# Generated by Django 5.2 on 2025-08-04 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0177_ibmqradarassetsgroup_integration"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassetsgroup",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ibmqradarassetsgroup",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
