# Generated by Django 5.2 on 2025-08-04 07:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0178_ibmqradarassetsgroup_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ibmqradarassetsgroup",
            name="child_group_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
