# Generated by Django 5.2 on 2025-08-04 09:55

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0179_alter_ibmqradarassetsgroup_child_group_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassests",
            name="group_ids",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.BigIntegerField(),
                blank=True,
                default=list,
                null=True,
                size=None,
            ),
        ),
    ]
