# Generated by Django 5.2 on 2025-08-07 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0021_alter_integration_integration_type_and_more"),
        ("tenant", "0180_ibmqradarassests_group_ids"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="duibmqradartenants",
            unique_together={("db_id", "integration")},
        ),
    ]
