# Generated by Django 5.2 on 2025-08-07 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0021_alter_integration_integration_type_and_more"),
        ("tenant", "0186_alter_ibmqradaroffense_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="duitsmtenants",
            unique_together={("db_id", "integration")},
        ),
    ]
