# Generated by Django 5.2 on 2025-08-27 05:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0188_alter_duitsmfinaltickets_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskExecutionLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_name",
                    models.CharField(
                        choices=[
                            ("qradar_sync", "QRadar Sync"),
                            ("qradar_admin_eps", "QRadar Admin EPS"),
                            ("qradar_tenant_eps", "QRadar Tenant EPS"),
                            ("qradar_daily_sync", "QRadar Daily Sync"),
                            ("itsm_sync", "ITSM Sync"),
                            ("cortex_sync", "Cortex SOAR Sync"),
                            ("threat_intel_default", "Threat Intelligence Default"),
                            ("threat_intel_tenant", "Threat Intelligence Tenant"),
                            ("threat_intel_all", "Threat Intelligence All"),
                        ],
                        help_text="Unique identifier for the task type",
                        max_length=50,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="Human-readable name for the task", max_length=100
                    ),
                ),
                (
                    "last_started_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task was last started",
                        null=True,
                    ),
                ),
                (
                    "last_completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When the task was last completed successfully",
                        null=True,
                    ),
                ),
                (
                    "last_failed_at",
                    models.DateTimeField(
                        blank=True, help_text="When the task last failed", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("pending", "Pending"),
                        ],
                        default="pending",
                        help_text="Current status of the task",
                        max_length=20,
                    ),
                ),
                (
                    "execution_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this task has been executed",
                    ),
                ),
                (
                    "success_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of successful executions"
                    ),
                ),
                (
                    "failure_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of failed executions"
                    ),
                ),
                (
                    "last_error_message",
                    models.TextField(
                        blank=True,
                        help_text="Last error message if task failed",
                        null=True,
                    ),
                ),
                (
                    "duration_seconds",
                    models.FloatField(
                        blank=True,
                        help_text="Duration of last execution in seconds",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "task_execution_logs",
                "indexes": [
                    models.Index(
                        fields=["task_name"], name="task_execut_task_na_0eefcf_idx"
                    ),
                    models.Index(
                        fields=["last_completed_at"],
                        name="task_execut_last_co_77d162_idx",
                    ),
                    models.Index(
                        fields=["status"], name="task_execut_status_49d36c_idx"
                    ),
                ],
            },
        ),
    ]
