# Generated by Django 5.2 on 2025-08-27 05:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0189_taskexecutionlog"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskExecutionLog",
        ),
    ]
