# Generated by Django 5.2 on 2025-08-27 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0190_delete_taskexecutionlog"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_value", models.DateField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "date_storage",
            },
        ),
    ]
