# Generated by Django 5.2 on 2025-08-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0191_datestorage"),
    ]

    operations = [
        migrations.CreateModel(
            name="DateTimeStorage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime_value", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "datetime_storage",
            },
        ),
        migrations.DeleteModel(
            name="DateStorage",
        ),
    ]
