# Generated by Django 5.2 on 2025-09-02 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0192_datetimestorage_delete_datestorage"),
    ]

    operations = [
        migrations.AddField(
            model_name="ibmqradarassests",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Whether the asset is currently reporting/active",
            ),
        ),
    ]
