# Generated by Django 5.2 on 2025-09-10 04:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0193_ibmqradarassests_is_active"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SourceIPGeoLocation",
        ),
    ]
