# Generated by Django 5.2 on 2025-09-14 04:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0023_integration_created_by_integration_modified_by"),
        ("tenant", "0194_delete_sourceipgeolocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="IBMQradarDailyEPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_eps", models.FloatField(default=0)),
                ("peak_eps", models.FloatField(default=0)),
                ("qradar_end_time", models.DateTimeField()),
                (
                    "created_at",
                    models.DateTimeField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_daily_eps",
                        to="tenant.duibmqradartenants",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_ibm_qradar_daily_eps",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "du_ibm_qradar_daily_eps",
            },
        ),
    ]
