# Generated by Django 5.2 on 2025-09-21 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0195_ibmqradardailyeps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantrolepermissions",
            name="permission",
            field=models.IntegerField(
                choices=[
                    (1, "Dashboard"),
                    (3, "Reports"),
                    (4, "Threat Intelligence"),
                    (5, "Assets"),
                ]
            ),
        ),
    ]
