# Generated by Django 5.2 on 2025-09-22 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0196_alter_tenantrolepermissions_permission"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomerEPS",
        ),
    ]
