# Generated by Django 5.2 on 2025-09-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0197_delete_customereps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="duibmqradartenants",
            name="db_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ibmqradarassests",
            name="db_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ibmqradarassetsgroup",
            name="db_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ibmqradareventcollector",
            name="db_id",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="ibmqradarlogsourcetypes",
            name="db_id",
            field=models.IntegerField(),
        ),
    ]
