# Generated by Django 5.2 on 2025-10-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0198_alter_duibmqradartenants_db_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ducortexsoarincidentfinalmodel",
            name="close_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
