# Generated by Django 5.2 on 2026-01-14 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0024_alter_integration_soar_subtype"),
        ("tenant", "0199_ducortexsoarincidentfinalmodel_close_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="FortiSOARTenants",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.UUIDField(unique=True)),
                ("name", models.CharField(blank=True, default=None, max_length=255)),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_forti_soar_tenants",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "du_forti_soar_tenants",
            },
        ),
    ]
