# Generated by Django 5.2 on 2026-01-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0024_alter_integration_soar_subtype"),
        ("tenant", "0200_fortisoartenants"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="FortiSOARTenants",
            new_name="DUFortiSOARTenants",
        ),
        migrations.CreateModel(
            name="DUFortiSOARIncidentModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("db_id", models.IntegerField(blank=True, null=True)),
                ("created", models.DateTimeField()),
                ("modified", models.DateTimeField()),
                ("account", models.CharField(blank=True, max_length=255, null=True)),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=50, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("occured", models.DateTimeField(blank=True, null=True)),
                ("closed", models.DateTimeField(blank=True, null=True)),
                ("sla", models.IntegerField(blank=True, null=True)),
                ("severity", models.IntegerField(blank=True, null=True)),
                ("investigated_id", models.IntegerField(blank=True, null=True)),
                (
                    "closing_user_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("owner", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "playbook_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "incident_phase",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "incident_priority",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("incident_tta", models.DateTimeField(blank=True, null=True)),
                ("incident_ttdn", models.DateTimeField(blank=True, null=True)),
                ("incident_ttn", models.DateTimeField(blank=True, null=True)),
                ("initial_notification", models.BooleanField(null=True)),
                (
                    "itsm_sync_status",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("list_of_rules_offense", models.JSONField(blank=True, null=True)),
                ("log_source_type", models.JSONField(blank=True, null=True)),
                (
                    "low_level_categories_events",
                    models.JSONField(blank=True, null=True),
                ),
                ("source_ips", models.JSONField(blank=True, null=True)),
                (
                    "qradar_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "qradar_sub_category",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tta_calculation",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "mitre_tactic",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "mitre_technique",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "configuration_item",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("close_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cortex_soar_tenant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_forti_soar_incidents",
                        to="tenant.dufortisoartenants",
                    ),
                ),
                (
                    "integration",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="du_forti_soar_incidents",
                        to="integration.integration",
                    ),
                ),
            ],
            options={
                "db_table": "du_forti_soar_incidents",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "db_id"),
                        name="forti_soar_unique_account_db_id",
                    )
                ],
            },
        ),
    ]
