# Generated by Django 5.2 on 2026-01-20 17:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0201_rename_fortisoartenants_dufortisoartenants_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dufortisoarincidentmodel",
            old_name="cortex_soar_tenant",
            new_name="forti_soar_tenant",
        ),
    ]
