# Generated by Django 5.2 on 2026-01-21 06:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "tenant",
            "0202_rename_cortex_soar_tenant_dufortisoarincidentmodel_forti_soar_tenant",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dufortisoarincidentmodel",
            name="analysis_notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
