# Generated by Django 5.2 on 2026-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0203_dufortisoarincidentmodel_analysis_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="forti_soar_tenants",
            field=models.ManyToManyField(blank=True, to="tenant.dufortisoartenants"),
        ),
    ]
