# Generated by Django 5.2 on 2026-02-03 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("integration", "0024_alter_integration_soar_subtype"),
        ("tenant", "0204_company_forti_soar_tenants"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="ducortexsoarincidentfinalmodel",
            name="unique_account_db_id",
        ),
        migrations.RemoveConstraint(
            model_name="dufortisoarincidentmodel",
            name="forti_soar_unique_account_db_id",
        ),
        migrations.AlterUniqueTogether(
            name="ducortexsoartenants",
            unique_together={("db_id", "integration")},
        ),
        migrations.AlterUniqueTogether(
            name="dufortisoartenants",
            unique_together={("db_id", "integration")},
        ),
        migrations.AddConstraint(
            model_name="ducortexsoarincidentfinalmodel",
            constraint=models.UniqueConstraint(
                fields=("account", "db_id", "integration"), name="unique_account_db_id"
            ),
        ),
        migrations.AddConstraint(
            model_name="dufortisoarincidentmodel",
            constraint=models.UniqueConstraint(
                fields=("account", "db_id", "integration"),
                name="forti_soar_unique_account_db_id",
            ),
        ),
    ]
