# Generated by Django 5.2 on 2026-02-10 05:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "tenant",
            "0205_remove_ducortexsoarincidentfinalmodel_unique_account_db_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="soartenantslametric",
            unique_together={("company", "sla_level")},
        ),
        migrations.RemoveField(
            model_name="soartenantslametric",
            name="soar_tenant",
        ),
    ]
