# Generated by Django 5.2 on 2026-02-10 05:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0206_alter_soartenantslametric_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dufortisoarincidentmodel",
            name="offense_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
