# Generated by Django 5.2 on 2026-02-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tenant", "0207_dufortisoarincidentmodel_offense_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="dufortisoarincidentmodel",
            name="ticket_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
