# Generated by Django 5.2 on 2025-04-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="permission",
            field=models.IntegerField(
                choices=[
                    (1, "Dashboard"),
                    (2, "Chatbot"),
                    (3, "Reports"),
                    (4, "Threat Intelligence"),
                    (5, "Assets"),
                ],
                default=1,
            ),
        ),
        migrations.AddField(
            model_name="rolepermission",
            name="permission_text",
            field=models.CharField(
                default="Dashboard",
                editable=False,
                help_text="Automatically set to the text label of the permission choice",
                max_length=100,
            ),
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
    ]
