# Generated by Django 5.2 on 2025-04-15 07:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_user_groups_user_is_active_user_is_staff_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_staff",
            new_name="is_tenant",
        ),
    ]
