# Generated by Django 5.2 on 2025-05-23 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0005_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="company_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
