# Generated by Django 5.2 on 2025-06-02 06:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0007_alter_user_email_alter_user_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="hashed_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
