# Generated by Django 5.2 on 2025-06-30 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0009_user_is_deleted"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="company_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="profile_picture",
        ),
    ]
