# Generated by Django 5.2 on 2025-09-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0010_remove_user_company_name_remove_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_read_only",
            field=models.BooleanField(default=False),
        ),
    ]
