# Generated by Django 5.2 on 2025-09-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0011_user_is_read_only"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rolepermission",
            name="permission",
            field=models.IntegerField(
                choices=[
                    (1, "Dashboard"),
                    (3, "Reports"),
                    (4, "Threat Intelligence"),
                    (5, "Assets"),
                ],
                default=1,
            ),
        ),
    ]
